#!/bin/sh

PROJECT=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`
STAGED_FILES_CMD=`git diff --name-only --diff-filter=ACMR HEAD | grep .php$`
SFILES=${SFILES:-$STAGED_FILES_CMD}


composer pre-commit
if [ $? != 0 ]
then
    echo "Fix the errors before commit."
    exit 1
fi
exit $?
